Repository ucsb-cs156-f24/proj-rec-f24-06, pull requests merged in 2024-11, with the labels that each got.

#31 CL - Added professor and student to user database table
  src/main/java/edu/ucsb/cs156/rec/entities/User.java
  src/main/resources/db/migration/changes/Users.json
Labels: FIXME-PR title, FIXME-Team CR, FIXME-PR Description

#62 Individual Roles for Users, Change Role Capabilities, User Table for Admins
  frontend/src/App.js
  frontend/src/fixtures/usersFixtures.js
  frontend/src/main/components/Users/UsersTable.js
  frontend/src/tests/components/Users/UsersTable.test.js
  src/main/java/edu/ucsb/cs156/rec/config/SecurityConfig.java
  src/main/java/edu/ucsb/cs156/rec/controllers/UsersController.java
  src/main/java/edu/ucsb/cs156/rec/entities/User.java
  src/main/java/edu/ucsb/cs156/rec/interceptors/RoleInterceptor.java
  src/main/java/edu/ucsb/cs156/rec/interceptors/RoleInterceptorConfig.java
  src/main/java/edu/ucsb/cs156/rec/repositories/UserRepository.java
  src/main/resources/db/migration/changes/Users.json
  src/test/java/edu/ucsb/cs156/rec/controllers/UsersControllerTests.java
  src/test/java/edu/ucsb/cs156/rec/interceptors/RoleInterceptorTests.java
Labels: 20

#55 CL: Add RequestType table (db migration, entity, repository)
  src/main/java/edu/ucsb/cs156/rec/RequestTypeApplicationRunner.java
  src/main/java/edu/ucsb/cs156/rec/entities/RequestType.java
  src/main/java/edu/ucsb/cs156/rec/repositories/RequestTypeRepository.java
  src/main/java/edu/ucsb/cs156/rec/services/RequestTypeService.java
  src/main/resources/db/migration/changes/RequestType.json
  src/test/java/edu/ucsb/cs156/rec/RequestTypeApplicationRunnerTests.java
  src/test/java/edu/ucsb/cs156/rec/services/RequestTypeServiceTests.java
Labels: 20, Merge Candidate-CI

#68 eg - placeholder requests page for admin to see all recommendation requests
  frontend/src/App.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/pages/AdminRequestsPage.js
  frontend/src/stories/pages/Admin/AdminRequestsPage.stories.js
  frontend/src/tests/pages/AdminRequestsPage.test.js
Labels: 5, Merge Candidate-CI

#69 CL: Add RequestTypeController for CRUD operations
  src/main/java/edu/ucsb/cs156/rec/controllers/RequestTypeController.java
  src/test/java/edu/ucsb/cs156/rec/controllers/RequestTypeControllerTests.java
Labels: 10, Merge Candidate-CI

#72 CL: Create RequestTypeForm (team02 style)
  frontend/src/fixtures/requesttypeFixtures.js
  frontend/src/main/components/RequestType/RequestTypeForm.js
  frontend/src/stories/components/RequestType/RequestTypeForm.stories.js
  frontend/src/tests/components/RequestType/RequestTypeForm.test.js
Labels: Ready-For-Staff

#77 CL: Copy Placeholders for RequestType pages; add to App.js/AppNavbar.js
  frontend/src/App.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/pages/RequestType/RequestTypeCreatePage.js
  frontend/src/main/pages/RequestType/RequestTypeEditPage.js
  frontend/src/main/pages/RequestType/RequestTypeIndexPage.js
  frontend/src/tests/components/Nav/AppNavbar.test.js
  frontend/src/tests/pages/RequestType/RequestTypeCreatePage.test.js
  frontend/src/tests/pages/RequestType/RequestTypeEditPage.test.js
  frontend/src/tests/pages/RequestType/RequestTypeIndexPage.test.js
Labels: 10, Merge Candidate-CI

#88 eg - professor tab on navbar, three placeholders pages for pending requests, completed requests, and statistics pages
  frontend/src/App.js
  frontend/src/fixtures/currentUserFixtures.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/pages/Professor/ProfessorCompletedRequestsPage.js
  frontend/src/main/pages/Professor/ProfessorPendingRequestsPage.js
  frontend/src/main/pages/Professor/ProfessorStatisticsPage.js
  frontend/src/stories/pages/Professor/ProfessorCompletedRequestsPage.stories.js
  frontend/src/stories/pages/Professor/ProfessorPendingRequestsPage.stories.js
  frontend/src/stories/pages/Professor/ProfessorStatisticsPage.stories.js
  frontend/src/tests/components/Nav/AppNavbar.test.js
  frontend/src/tests/pages/Professor/ProfessorCompletedRequestsPage.test.js
  frontend/src/tests/pages/Professor/ProfessorPendingRequestsPage.test.js
  frontend/src/tests/pages/Professor/ProfessorStatisticsPage.test.js
Labels: 5, Merge Candidate-CI, Ready-For-Staff

#93 pc/vp - create new branch from Victor's old branch with only the Pending Request Table
  frontend/src/fixtures/pendingrequestsFixtures.js
  frontend/src/main/components/PendingRequests/PendingRequestsTable.js
  frontend/src/stories/components/PendingRequests/PendingRequestsTable.stories.js
  frontend/src/tests/components/PendingRequests/PendingRequestsTable.test.js
Labels: 5, Merge Candidate-CI, Ready-For-Staff

#94 vp - added Accept and Deny buttons and functionality to Pending Requests Table
  frontend/src/main/components/PendingRequests/PendingRequestsTable.js
  frontend/src/tests/components/PendingRequests/PendingRequestsTable.test.js
Labels: 5
